### ISSUE TITLE
jsonrpc support for name preorders/ registrations

### ISSUE THREAD

**Issue by ig-grant** [namesystem/blockstore#86]
Are there any plans for jsonrpc support for name operations (preorders, registrations etc.)? A simple wrapper around blockstore-cli perhaps?

**Comment by muneeb-ali** [comment]
blockstored already responds with json and blockstore-cli is a client that reads the json data

See 
> BlockstoredRPC(jsonrpc.JSONRPC) 

in [this file](https://github.com/namesystem/blockstore/blob/master/blockstore/blockstored.py) for details on the format etc. Feel free to close the issue if you think this answers your question.

**Comment by ig-grant** [comment]
Thanks Muneeb - I'll take a look at this.

I was thinking of an HTTP endpoint that listens for name preorder/registration requests, so an HTTP client could be used.

**Comment by muneeb-ali** [comment]
You can have a HTTP wrapper around this. In fact, enabling that in the current implementation is very easy since Twisted supports HTTP calls very easily. We explicitly decided to not use HTTP and you're welcome to open an issue with the label "discussion" to chat about this design choice. 

If all sounds good re jsonrpc, please close this issue. Thanks!

**Comment by ig-grant** [comment]
This is great, thanks - I'll close the issue.
